### ISSUE TITLE
URL is not defined in swarm-node

### ISSUE THREAD

**Issue by justinmchase** [MainframeHQ/erebos#55]
Just trying to import the module causes null reference exceptions:
```sh
justin@justin-server:~/code/test$ node -r babel-register .
/home/justin/code/test/node_modules/@erebos/api-bzz-base/cjs/index.js:76
    this._url = new URL(url).toString();
                    ^

ReferenceError: URL is not defined
    at new BaseBzz (/home/justin/code/test/node_modules/@erebos/api-bzz-base/cjs/index.js:76:21)
    at new Bzz (/home/justin/code/test/node_modules/@erebos/api-bzz-node/lib/index.js:24:5)
    at new NodeClient (/home/justin/code/test/node_modules/@erebos/swarm-node/lib/Client.js:60:23)
    at Object.<anonymous> (/home/justin/code/test/index.js:4:16)
    at Module._compile (module.js:635:30)
    at loader (/home/justin/code/test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/justin/code/test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

Also I had to manually install `rxjs`, that appears to be a dependency which isn't actually listed in the project.json file so npm doesn't install it automatically.

The code in index.js:
```js
import { SwarmClient } from '@erebos/swarm-node'

const client = new SwarmClient({ bzz: 'http://localhost:30399' })

client.bzz
  .upload('Hello world!', { contentType: 'text/plain' })
  .then(hash => console.log('hash:', hash) || client.bzz.download(hash))
  .then(res => res.text())
  .then(text => {
    console.log(text) // "Hello world!"
  })
```

**Comment by cayblood** [comment]
@justinmchase @avclarke reports that the problems you are experiencing are most likely due to a node version issue. Erebos needs 10+. Can you please try that and return and report?

**Comment by justinmchase** [comment]
Ok, I'll try it later tonight, I was using v8

**Comment by justinmchase** [comment]
Ok, I got it working!

I had to add this to my container to make it listen on the right device:
```yml
    command:
      - "--httpaddr 0.0.0.0"
```

**Comment by cayblood** [comment]
Thanks for the follow-up @justinmchase !
